import java.awt.Color;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rohan.aney
 */
public class getTableDisplay extends javax.swing.JFrame {

    /**
     * Creates new form getTableDisplay
     */
    public getTableDisplay() {
        initComponents();
    }
    
    public static DefaultTableModel buildTableModel(ResultSet rs)
	        throws SQLException {

    	 DefaultTableModel tableModel = new DefaultTableModel();
    	 ResultSetMetaData metaData = rs.getMetaData();
    	 int columnCount = metaData.getColumnCount();
    	 for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++){
             tableModel.addColumn(metaData.getColumnLabel(columnIndex));
         }
    	 Object[] row = new Object[columnCount];
    	 while (rs.next()){
             //Get object from column with specific index of result set to array of objects
             for (int i = 0; i < columnCount; i++){
                 row[i] = rs.getObject(i+1);
             }
             //Now add row to table model with that array of objects as an argument
             tableModel.addRow(row);
            // table.setModel(tableModel);
             
    	 }
    	 return tableModel;
    	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	this.getContentPane().setBackground(Color.decode("#3a4660"));
        jStudnetButton = new javax.swing.JButton();
        jStudnetButton.setBackground(Color.decode("#feda6a"));
        jClassesButton = new javax.swing.JButton();
        jClassesButton.setBackground(Color.decode("#feda6a"));
        jTasButton = new javax.swing.JButton();
        jTasButton.setBackground(Color.decode("#feda6a"));
        jPrequButton = new javax.swing.JButton();
        jPrequButton.setBackground(Color.decode("#feda6a"));
        jCoursesButton = new javax.swing.JButton();
        jCoursesButton.setBackground(Color.decode("#feda6a"));
        jEnrollButton = new javax.swing.JButton();
        jEnrollButton.setBackground(Color.decode("#feda6a"));
        jLogsButton = new javax.swing.JButton();
        jLogsButton.setBackground(Color.decode("#feda6a"));
        jScrollPane1 = new javax.swing.JScrollPane();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jStudnetButton.setText("Students");
        jStudnetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStudnetButtonActionPerformed(evt);
            }
        });

        jClassesButton.setText("Classes");
        jClassesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClassesButtonActionPerformed(evt);
            }
        });

        jTasButton.setText("TAs");
        jTasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTasButtonActionPerformed(evt);
            }
        });

        jPrequButton.setText("Prerequisites");
        jPrequButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPrequButtonActionPerformed(evt);
            }
        });

        jCoursesButton.setText("Courses");
        jCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCoursesButtonActionPerformed(evt);
            }
        });

        jEnrollButton.setText("Enrollment");
        jEnrollButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEnrollButtonActionPerformed(evt);
            }
        });

        jLogsButton.setText("Logs");
        jLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        
		layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jStudnetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(jClassesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTasButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(210, 210, 210)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPrequButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCoursesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEnrollButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLogsButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStudnetButton)
                    .addComponent(jPrequButton))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jClassesButton)
                    .addComponent(jCoursesButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTasButton)
                    .addComponent(jEnrollButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLogsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStudnetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStudnetButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayStudents(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jStudnetButtonActionPerformed

    private void jCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCoursesButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayCourses(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jCoursesButtonActionPerformed

    private void jClassesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClassesButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayClasses(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jClassesButtonActionPerformed

    private void jTasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTasButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayTAs(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jTasButtonActionPerformed

    private void jLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogsButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayLogs(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jLogsButtonActionPerformed

    private void jPrequButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPrequButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayPrerequisites(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jPrequButtonActionPerformed

    private void jEnrollButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEnrollButtonActionPerformed
        // TODO add your handling code here:
    	JTable jt=null;
    	try {
   		 jt=new JTable(buildTableModel(Driver.displayEnrollments(Driver.getConn())));
   		 jScrollPane1.setViewportView(jt);
       	 //getContentPane().add(new JScrollPane(jt),BorderLayout.CENTER);
       	 //pack();
       	}//GEN-LAST:event_jButton1ActionPerformed
       	catch(Exception e) {
       		JOptionPane.showMessageDialog(null, "Cross Check Values");
       	}
    }//GEN-LAST:event_jEnrollButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getTableDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(getTableDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(getTableDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(getTableDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new getTableDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClassesButton;
    private javax.swing.JButton jCoursesButton;
    private javax.swing.JButton jEnrollButton;
    private javax.swing.JButton jLogsButton;
    private javax.swing.JButton jPrequButton;
    private javax.swing.JButton jStudnetButton;
    private javax.swing.JButton jTasButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
